### PR TITLE
Some fixes and improvements

### LINKED ISSUE #165: Bug MC-153230
This mod reintroduces bug [MC-153230](https://bugs.mojang.com/browse/MC-153230). This was fixed in 1.16.2 but if you use the latest version of this mod in 1.16.5 the bug is still there.

### LINKED ISSUE #184: Mod carpet-extra is only using deprecated 'modmenu:parent' custom value!
The mod `carpet-extra-1.16.5-1.4.27` causes Fabric to output the following to the game log:
`WARNING! Mod carpet-extra is only using deprecated 'modmenu:parent' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.`

As it says in the line above, if you want to be able to update to Minecraft 1.18 or above, you will have to make some changes to the mod's metadata, located here:
https://github.com/gnembon/carpet-extra/blob/8abea2626cea6325bce9852b7b49acaa1a392f60/src/main/resources/fabric.mod.json#L35-L37

### PR DESCRIPTION
**Pull request by manyrandomthings**
* Removes useless mixins
* Uses fabric loader for initializing instead of noop mixins
* Removes unused code
* Moved assets to carpet-extra folder
* Fixed modmenu parent and added link to issues
* Fixed a crash with alternative block placement

Probably Fixes #165 
Fixes #184

### CODE REVIEW

File: src/main/java/carpetextra/helpers/ObsidianBlock.java [hunk 1]
```diff
@@ -21,14 +21,11 @@ public ObsidianBlock(Settings settings)
     }
     
     @Override
-    public boolean hasRandomTicks(BlockState state)
+    public void randomTick(BlockState blockState_1, ServerWorld serverWorld_1, BlockPos blockPos_1, Random random_1)
     {
-        return CarpetExtraSettings.renewableLava;
-    }
+        if(!CarpetExtraSettings.renewableLava)
+            return;
```
Comment (altrisi) [inline src/main/java/carpetextra/helpers/ObsidianBlock.java:27]: Why is this better? Haven't looked at random ticks for quite a while, but IIRC I think then random ticks to obsidian would count towards the limit, but not execute since they would just return (therefore resulting in non-vanilla behaviour). Would need checking though. Or was it failing else?

File: src/main/java/carpetextra/mixins/AnimalMateGoalMixin.java [hunk 2]
```diff
@@ -1,17 +0,0 @@
...
-import org.spongepowered.asm.mixin.Mixin;
-import org.spongepowered.asm.mixin.Shadow;
-import org.spongepowered.asm.mixin.injection.At;
-import org.spongepowered.asm.mixin.injection.Inject;
-import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;
-
-@Mixin(AnimalMateGoal.class)
-public abstract class AnimalMateGoalMixin {
-    //intentionally left blank
-}
```
Comment (altrisi) [inline src/main/java/carpetextra/mixins/AnimalMateGoalMixin.java:17]: Hm... This says "intentionally left blank", so it may have a reason to exist. IIRC this was, in its time to prevent NPEs in dispenser feeds animals rules, though it was changed to more specific mixins/just other mixins at some point.

File: src/main/java/carpetextra/utils/RulePrinter.java [hunk 3]
```diff
@@ -10,7 +10,7 @@
     @Override
     public void onInitialize() {
         System.setOut(CarpetRulePrinter.OLD_OUT);
-        CarpetExtraServer.noop();
+        CarpetServer.manageExtension(new CarpetExtraServer());
```
Comment (altrisi) [inline src/main/java/carpetextra/utils/RulePrinter.java:13]: You should call `onInitialize()` here. Even if it does exactly that, maybe at some point extra instructions are added, or the class name is changed, etc.

File: src/main/resources/fabric.mod.json [hunk 4]
```diff
@@ -29,10 +31,9 @@
     "carpet": "*",
     "minecraft": "1.16.x"
   },
-  "suggests": {
-    "flamingo": "*"
-  },
```
Comment (altrisi) [inline src/main/resources/fabric.mod.json:34]: Why though? It doesn't hurt anyone.

File: src/main/java/carpetextra/helpers/ObsidianBlock.java (hunk 1 above)
Comment (altrisi) [reply src/main/java/carpetextra/helpers/ObsidianBlock.java:27]: Other vanilla blocks seems to do exactly what was here before, check for example `NetherWartBlock`

**Review by altrisi — COMMENTED** [review]
My point of view of the PR.

File: src/main/java/carpetextra/helpers/ObsidianBlock.java (hunk 1 above)
Comment (manyrandomthings) [reply src/main/java/carpetextra/helpers/ObsidianBlock.java:27]: I changed this because `hasRandomTicks()` is already set to true from `ticksRandomly()` in the block settings, but I suppose using it might be better

File: src/main/java/carpetextra/mixins/AnimalMateGoalMixin.java (hunk 2 above)
Comment (manyrandomthings) [reply src/main/java/carpetextra/mixins/AnimalMateGoalMixin.java:17]: This mixin wasn't even defined in carpet-extra.mixins.json, plus it has no methods and does nothing, like the WetSpongeBlockMixin that I also removed

File: src/main/java/carpetextra/utils/RulePrinter.java (hunk 3 above)
Comment (manyrandomthings) [reply src/main/java/carpetextra/utils/RulePrinter.java:13]: To call `onInitialize()` would require doing `new CarpetExtraServer().onInitialize();`, which seems pointless since I can just have `new CarpetExtraServer()` here. Plus there might be things in onInitialize that don't need to be loaded to print the list of rules. I can move this line to a static method in CarpetExtraServer if that would work better though

Comment (altrisi) [reply src/main/java/carpetextra/utils/RulePrinter.java:13]: The new instance is basically what loader would do anyway, that's at least what I would have done. Believe me, it's better to run it as if it was a natural startup just before, else it can cause the action to fail in the future (this is for the rules-to-readme action that keeps the Readme updated, where Loader doesn't know about the other entrypoint since fabric.mod.json is completely replaced)

File: src/main/java/carpetextra/helpers/ObsidianBlock.java (hunk 1 above)
Comment (altrisi) [reply src/main/java/carpetextra/helpers/ObsidianBlock.java]: `ticksRandomly` is a function that enables the randomticks for the `AbstractBlock.Settings` instance, which isn't called in obsidian's (default value being `false`.

File: src/main/resources/fabric.mod.json (hunk 4 above)
Comment (DragonEggBedrockBreaking) [reply src/main/resources/fabric.mod.json:34]: > Why though?

Why not?

File: src/main/java/carpetextra/mixins/AnimalMateGoalMixin.java (hunk 2 above)
Comment (gnembon) [reply src/main/java/carpetextra/mixins/AnimalMateGoalMixin.java:17]: The reason it was 'intentionally left blank' was to help in switching from 1.15 (then master) and 1.16 (then future) branches. Just forgot to remove it when 1.16 was the only version.

In general, my experience is that if Mojang implements some of the carpet features in a snapshot, its better to 'comment out' the feature then remove all the signs of it in the cod cause then when you switch back and forth between master and future branches that causes merge conflicts.

**Review by gnembon — APPROVED** [review]

**Review by altrisi — APPROVED** [review]
